/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebar-layout'
import { Route as SidebarLayoutChatLayoutRouteImport } from './routes/_sidebar-layout._chat-layout'
import { Route as SidebarLayoutChatLayoutIndexRouteImport } from './routes/_sidebar-layout._chat-layout.index'
import { Route as SidebarLayoutChatLayoutChatIdRouteImport } from './routes/_sidebar-layout._chat-layout.$chatId'

const SidebarLayoutRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutChatLayoutRoute = SidebarLayoutChatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutChatLayoutIndexRoute =
  SidebarLayoutChatLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const SidebarLayoutChatLayoutChatIdRoute =
  SidebarLayoutChatLayoutChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar-layout': typeof SidebarLayoutRouteWithChildren
  '/_sidebar-layout/_chat-layout': typeof SidebarLayoutChatLayoutRouteWithChildren
  '/_sidebar-layout/_chat-layout/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/_sidebar-layout/_chat-layout/': typeof SidebarLayoutChatLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$chatId'
  id:
    | '__root__'
    | '/_sidebar-layout'
    | '/_sidebar-layout/_chat-layout'
    | '/_sidebar-layout/_chat-layout/$chatId'
    | '/_sidebar-layout/_chat-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarLayoutRoute: typeof SidebarLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar-layout': {
      id: '/_sidebar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout/_chat-layout': {
      id: '/_sidebar-layout/_chat-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/_chat-layout/': {
      id: '/_sidebar-layout/_chat-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutIndexRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/_sidebar-layout/_chat-layout/$chatId': {
      id: '/_sidebar-layout/_chat-layout/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof SidebarLayoutChatLayoutChatIdRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
  }
}

interface SidebarLayoutChatLayoutRouteChildren {
  SidebarLayoutChatLayoutChatIdRoute: typeof SidebarLayoutChatLayoutChatIdRoute
  SidebarLayoutChatLayoutIndexRoute: typeof SidebarLayoutChatLayoutIndexRoute
}

const SidebarLayoutChatLayoutRouteChildren: SidebarLayoutChatLayoutRouteChildren =
  {
    SidebarLayoutChatLayoutChatIdRoute: SidebarLayoutChatLayoutChatIdRoute,
    SidebarLayoutChatLayoutIndexRoute: SidebarLayoutChatLayoutIndexRoute,
  }

const SidebarLayoutChatLayoutRouteWithChildren =
  SidebarLayoutChatLayoutRoute._addFileChildren(
    SidebarLayoutChatLayoutRouteChildren,
  )

interface SidebarLayoutRouteChildren {
  SidebarLayoutChatLayoutRoute: typeof SidebarLayoutChatLayoutRouteWithChildren
}

const SidebarLayoutRouteChildren: SidebarLayoutRouteChildren = {
  SidebarLayoutChatLayoutRoute: SidebarLayoutChatLayoutRouteWithChildren,
}

const SidebarLayoutRouteWithChildren = SidebarLayoutRoute._addFileChildren(
  SidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRoute: SidebarLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
